### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by phoe** [taviso/123elf#105]
This code is pretty much useless without licensing information. Is it even possible to contact the original owners, or is this project considered abandonware altogether?

**Comment by taviso** [comment]
It's abandonware.

I don't have a solution sorry, I wish I did.

**Comment by j0hnd3v** [comment]
lotus 123 creator Mitch Kapor is an active twitter user and mastodon. Perhaps he will provide a path with regards to licensing.

**Comment by phoe** [comment]
I got the following info from Mitch on the Fediverse:

> I left Lotus in 1987.  IBM bought the company in 1995 and retired 1-2-3 and its successors quite a while ago.   I doubt that anyone at IBM knows or cares about any of this.  I agree it's "abandonware".
