### ISSUE TITLE
Wiki: How to enter a formula that starts with a cell reference?

### ISSUE THREAD

**Issue by jhartzell42** [taviso/123elf#116]
If I want to have C1 be A1+B1, and I just type A1+B1, it assumes I want a label. I think there is probably some way to make it know I want to write a value instead, but this is not mentioned in the wiki intro. How do you do this, and can this be added to the Value section of the wiki?

Thanks in advance, and excited to learn how to use this spreadsheet program!

**Comment by taviso** [comment]
Thanks - good idea, I'll add that!

You usually do `+A1+B1`, but parens, numbers `@` (functions) all also work!

**Comment by taviso** [comment]
Done!

https://github.com/taviso/123elf/wiki/Getting-Started#values-and-formulas

A formula can also start with parens `()` or logical operators, `#`, but I don't want to overwhelm people with information in the Getting Started page 😄
