### ISSUE TITLE
lotus123r3_1.0-4bionic_i386.deb does not install on 32bit system

### ISSUE THREAD

**Issue by krackout** [taviso/123elf#117]
I tried installing `lotus123r3_1.0-4bionic_i386.deb` on a schrooted 32bit env. I got an error, unresolved dependencies libtinfo5 or 6 or lib32tinfo5 or 6 missing. Yet libtinfo5 was installed.

I noticed an (i) missing on control file.

So I extracted the .deb archive and changed `control` file.  
libtinfo5:386 -> libtinfo5:i386

After packing again, the installation proceeded, everything is fine. Thank you for all the work!

**Comment by taviso** [comment]
Oops - that was a bad typo, thank you!

I've fixed it now.
