### ISSUE TITLE
Appreciation; signal handling issues; typo in linux/unix flags translation?

### ISSUE THREAD

**Issue by OnesuchDev** [taviso/123elf#121]
I assume you meant "unixflags & 8" here?
https://github.com/taviso/123elf/blob/f851cb239a6242f9b5a8497dbe8209d2069f037b/wrappers.c#L166

I think this project is hilarious and an incredible technical achievement. I wonder whether the wrappers from it could help ~~put Xinuos out of business~~ people stuck using SCO OpenServer/UnixWare transition to Linux if they have lost source code to their applications. This might actually be even easier for newer software that uses ELF, since you could use wrappers around glibc (and/or potentially code from illumos) to generate a libc.so replacement that would translate structures/constants/etc.

**Comment by OnesuchDev** [comment]
Also, your signal wrapper should use sysv_signal. https://linux.die.net/man/3/sysv_signal

In some places it's stated that Linux uses sysv signal semantics but actually this is only true for the syscall itself and not the glibc wrapper around it. https://man7.org/linux/man-pages/man2/signal.2.html

**Comment by taviso** [comment]
Oops - yes, that looks like a bug - thanks! Huh, I wonder what needed  that flag that hasn't been working properly... that must have been before I started adding tests to check for breakage.. oops :)

I wasn't familiar with sysv_signal() - I agree it makes sense to switch to it, I can't remember if I needed any hacks to get signals working reliably, but maybe that will save me from needing some in future!

**Comment by OnesuchDev** [comment]
sigpause has an incompatible API on BSD in relation to Linux/UNIX: https://man.freebsd.org/cgi/man.cgi?query=sigpause&sektion=2&format=html

Also gsignal/ssignal don't work right on Linux https://man7.org/linux/man-pages/man3/gsignal.3.html - I guess you would have to reimplement them.

**Comment by rruhle** [comment]
Would this affect the spreadsheet function @@(), which doesn't work in Linux?

**Comment by taviso** [comment]
Hmm, do you have an example formula that doesn't work?

I use it sometimes, e.g. `@@("A1")` works, and ranges like `@SUM(@@("A1..B1"))` works here.

**Comment by rruhle** [comment]
Managing range names, or checking names for a range becomes harder when not shown in status bar.

Since @cell(attributes) won't reveal range names, the legacy DOS 123 spreadsheet function @@() showed any names created for a cell address in top left status bar.  

While Linux shows the same referenced value at cell location containing @@() function, only cell address appears in top left status bar, no range name(s).

The larger the spreadsheet, the harder becomes to check names created for a range, with the alternative key sequence F5, F3, F3, and scrolling thru all range names to locate the intended cell address.

**Comment by taviso** [comment]
Hmm, I wasn't familiar with that!

I know that in `POINT` mode if you choose a range that has a name, and press F3, 123 will enter the name, does that help?

We could add a new attribute like `@CELL("name", D6)` in the next release if that would be useful? I guess the question is what to do if that cell/range doesn't have a name, or has multiple names!

Maybe we could just return `ERR` unless there is exactly one match?

**Comment by rruhle** [comment]
If earlier mentioned code wrappers are not causing spreadsheet function status anomaly, then my discussion can be moved or postponed to avoid hijacking the original question regarding code wrappers.

I created new issue named "Function status missing range name"
