### ISSUE TITLE
GoogleFinance()

### ISSUE THREAD

**Issue by jarkkojs** [taviso/123elf#129]
One feature that I love in Google Sheets is GoogleFinance(). I wonder how feasible it would be to have that function also in this program. I've done e.g. my tax reports using that function. It would be cool if I could write e.g. my tax report with this software, then upload to the Google Drive and look up to it later with the Sheets.

I guess to access whatever service GoogleFinance() is using to be authenticated to Google services using probably Oauth2 token?

**Comment by taviso** [comment]
There is `@SYSTEM()`, so I use things like `@VALUE(@SYSTEM("stocks.sh GOOGL"))*A3` to get stock prices.

And you don't have to hardcode things, you can do `@VALUE(@SYSTEM("stocks.sh " & A6))` (where A6 contains a ticker symbol)

`stocks.sh` is just a quick shellscript that does:

```sh
curl -s "https://www.google.com/finance/quote/${symbol}${exchange}" | htmlq --attribute data-last-price 'div[data-last-price]'
```

**Comment by jarkkojs** [comment]
Wow that does it for me :-) Thank you!

**Comment by jarkkojs** [comment]
T

**Comment by jarkkojs** [comment]
I dug this issue as I had to do some personal finances :-) Maybe material for documentation? It was a great tip or example...
