### ISSUE TITLE
/System doesnt work

### ISSUE THREAD

**Issue by taviso** [taviso/123elf#15]
/System is supposed to drop you to a command shell, useful for macros.

It almost works... sometimes, but not quite and the terminal messes up.

**Comment by jserv** [comment]
I attempted to override the symbol `shell` by the following patch:
```diff
--- a/patch.c
+++ b/patch.c
@@ -67,3 +67,8 @@ int display_column_labels()
                        displayed_window[18] - 1);
     return x_disp_txt_write(displayed_window[21], buf, 0);
 }
+
+int shell()
+{
+    return 0;
+}
--- a/undefine.lst
+++ b/undefine.lst
@@ -249,3 +249,4 @@ load_printer_drivers
 close_printer_drivers
 read_print_config_dir
 display_column_labels
+shell
```

`/System` would be no operation as expected, and the terminal no longer messes up. But, once inserting the call of [system(3)](https://man7.org/linux/man-pages/man3/system.3.html), I found something wrong, and Lotus 1-2-3 program complained the following:
> Error loading driver, file name - `/proc/self/cwd/root/lotus/123.v10/ri/USA-English/dr123txt.ri`

**Comment by taviso** [comment]
I think this might be an old bug, can you try `rm ~/.l123set` and see if it fixes it?

I also updated it to enable UNIX file mode by default.

**Comment by multizone-uk** [comment]
I can reproduce the orginal issue, as you say it almost works, messes the terminal up.

**Comment by taviso** [comment]
I think I've found a solution, working on it!
