### ISSUE TITLE
I don't understand the instructions

### ISSUE THREAD

**Issue by edbird** [taviso/123elf#19]
I really can't understand from the instructions what to do.

I am running a Debian 11 system. The output of `objdump --info | grep coff-i386` is blank. From this I assume I do not have a copy of binutils which supports `coff-i386`.

So what should I do next?

I won't go into explaining what I tried to do because this will just confuse matters.

**Comment by taviso** [comment]
Yes, sorry about that - Debian don't enable `coff-i386` support, if they did building would be very easy :(

- First, you need to build your own copy of `binutils`, download and extract this: https://ftp.gnu.org/gnu/binutils/binutils-2.38.tar.xz
- You need to build binutils with  `./configure --enable-targets=all` and then `make`.
- Now copy the `objcopy` and `objdump` binaries you just built from the binutils directory into the 123elf directory.
- Now copy `ld-new` from the `ld` directory into the 12elf directory, but rename it `ld`.

That should work, and now you can build it.

**Comment by taviso** [comment]
Oh - you can try just running the `binutils.sh` script, it might work but hasn't had much testing.

**Comment by edbird** [comment]
I have done both of the first two points: However I do not see any files called `objcopy` or `objdump` in the directory `binutils-2.38`. What am I missing?

Is this relevant?

```
WARNING: 'makeinfo' is missing on your system.

You should only need it if you modified a '.texi' file,...

Makefile:1466 doc/as.info Error 127
```

Sorry I can't copy and paste these from the VM in which this is running.

**Comment by taviso** [comment]
I think it's okay to ignore it - you don't need the documentation. I would just do `make -i` to say ignore the errors.

**Comment by mparson** [comment]
FWIW, I used your `binutils.sh` script on my Fedora 35 box and it worked perfectly.

**Comment by edbird** [comment]
I've had a play around with it again today. Telling make to ignore the errors fixed the build. Interesting program - thanks for bringing back a piece of history
