### ISSUE TITLE
Larger terminal window results in segmentation fault

### ISSUE THREAD

**Issue by jeff-hines** [taviso/123elf#22]
Using commit [199b81f](https://github.com/taviso/123elf/commit/199b81f400410d23b633ce00edd803bb4a327fd2).

I ran `git pull`, then `make clean` and then `make`, then copied the l123set file to my home directory before trying to run the program again.

Terminal size 80x24: Works fine
Terminal size 300x70 (zsh says it's an exit code 139):
```
                   -`                    jeff@archpad 
                  .o+`                   ------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: 20BWS0PJ00 ThinkPad T450s 
               `+oooooo:                 Kernel: 5.17.9-arch1-1 
               -+oooooo+:                Uptime: 16 mins 
             `/:-:++oooo+:               Packages: 626 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           WM: JWM 
         ./ooosssso++osssssso+`          Theme: Raleigh [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: Papirus [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: xterm 
      :osssssss/        osssso+++.       CPU: Intel i7-5600U (4) @ 3.200GHz 
     /ossssssss/        +ssssooo/-       GPU: Intel HD Graphics 5500 
   `/ossssso+/:-        -:/+osssso+-     Memory: 1173MiB / 11843MiB 
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/                           
 .`                                 `/                           


jeff@archpad ~/builds/123elf (git)-[main] % ./123
[1]    5338 segmentation fault (core dumped)  ./123
                                                   %                          
139 jeff@archpad ~/builds/123elf (git)-[main] %                            :( 
```
Output from `neofetch` is included in case it helps in some way.

**Comment by taviso** [comment]
Thanks, I can reproduce -- I had to zoom out a lot to make it crash, you must have good eyesight :)

I'll track down the bug, maybe I should cap it in main until I can figure it out just so it doesn't crash when people are testing it... hmm.

**Comment by rhaamo** [comment]
Same here, term size of 308 cols and 79 lines results in:
```
fish: Job 1, './123' terminated by signal SIGSEGV (Address boundary error)
```

More larger (368 * 95) results in `123: Memory full`

**Comment by taviso** [comment]
Okay, I have a patch for the crash, but not the `Memory full` issue yet - I can fix it, but it will take some debugging!

**Comment by systemcoord** [comment]
@taviso Nope, my eyesight isn't too great. I use Xterm (no modifications to font size) for this program because the keymaps are not present for my terminals of choice. Thanks a lot for looking at this, I will try the new commit soon.

**Comment by jeff-hines** [comment]
@taviso Updated to [0f3a264](https://github.com/taviso/123elf/commit/0f3a264cd05f6aeb4566b71f79a56490d341446a) and can confirm the program doesn't crash with > 256 columns.

Re: eyesight -- I'm using xterm with default settings, can barely read the terminal without squinting!
