### ISSUE TITLE
Fill in the banner template {INSERTNAME} {OS}, and so on.

### ISSUE THREAD

**Issue by taviso** [taviso/123elf#25]
This thing:

```
                           Lotus (R)   1-2-3 (R)   for {OS}
                                Version {PVERSION}
```

**Comment by jserv** [comment]
Once #26 is resolved, it does not matter as for banner since the package versions of Lotus 1-2-3 is never changed.

**Comment by taviso** [comment]
I'll close this issue, if someone wants to see the banner for nostalgia reasons they can still use -b.
