### ISSUE TITLE
SIGSEGV after TCGETS in fresh compile on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by josefcub** [taviso/123elf#3]
Hi!  I built binutils to support coff-i386, got all the dependencies lined up and compilation to succeed.   I've gotten as far as:

```
[=D][josefcub@sinir 123elf]$ ./123
Segmentation fault (core dumped)
```

I noticed that some options do work:

```
[=P][josefcub@sinir 123elf]$ ./123 -h
Usage: 123 [optional argument]
Optional arguments are:
        -f unix or -f dos       to select a file-name mode
        -c lower or -c upper    to select lower-case dos file-name mode
                                  or upper-case dos file-name mode
        -k keyboard-type        to select a particular keyboard type
        -n                      to run without using a video display
        -p number               to select the number of sheets displayed
                                  in perspective mode
        -w filename             to select a file to override the auto-file
```
        
(-n works as expected; the rest lead to a segfault).  When I ran strace, I ended up with this:

```
openat(AT_FDCWD, "/proc/self/cwd/root/lotus/123.v10/cbd/l_ascii.bun", O_RDONLY) = 4
statx(4, "", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT|AT_EMPTY_PATH, STATX_BASIC_STATS, {stx_mask=STATX_BASIC_STATS|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2910, ...}) = 0
read(4, "\\\v]\0\f\4-\0\4\0\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"..., 2910) = 2910
close(4)                                = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[SEGV], sa_flags=SA_RESTART}, {sa_handler=0x811a438, sa_mask=[SEGV], sa_flags=SA_RESTART}, 8) = 0
getpid()                                = 31626
kill(31626, SIGSEGV)                    = 0
sigreturn({mask=[]})                    = 24
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_USER, si_pid=31626, si_uid=1000} ---
+++ killed by SIGSEGV (core dumped) +++
```

I'm not much of a developer beyond being able to get this far, but I can provide other information (installed package versions, etc) if you need them.  I did change my TERM variable around, and even ran it from the Linux console, to see if TCGETS was hitting it with something that Konsole was providing, but no dice.

I realize you're on Fedora, and I'm on something a little different, so I'm just reporting this in the spirit of 'this might break soon for more than just me'.  

I've included the whole strace, in case it provides something I'm not seeing:
[strace.txt](https://github.com/taviso/123elf/files/8747944/strace.txt)
(The strace output differs here, probably due to `1>strace.txt 2>&1` )

Thank you for reading, and thanks for putting this really neat package together!

**Comment by taviso** [comment]
Interesting - thanks for the detailed report!

It looks like it's really close to working, it seems like it must have passed some unexpected options to ioctl. Maybe that's an easy fix, although I don't know why it did that.

**Comment by taviso** [comment]
Can you check if that commit fixes it? If not I'll try to get to an OpenSUSE machine sometime this weekend and see what's happening!

**Comment by josefcub** [comment]
That did the trick!  I really look forward to digging into this.  Thank you again!
![image](https://user-images.githubusercontent.com/39443735/169667659-b8ca45f8-98dd-4710-a456-9729cafc67c1.png)

**Comment by taviso** [comment]
No problem, glad you got it working! There are still lots of little things that don't work, please file an issue if you notice anything, I'm planning to work through them until it's fully working!
