### ISSUE TITLE
Keystrokes causing abnormal termination

### ISSUE THREAD

**Issue by sblendorio** [taviso/123elf#31]
When the spreadsheet is on the screen, press sequentially these keys:
- ESC
- [
- a

The result will be an abnormal program termination as per this screenshot:
![image](https://user-images.githubusercontent.com/2118813/170257892-c2a9dfa4-9684-4d17-ae90-4357c82a0c06.png)

**Comment by luizfeliperj** [comment]
I would add to this list SHIFT-TAB, this sequence also crash the program.

**Comment by taviso** [comment]
Can you test that and see if it fixes it?

**Comment by luizfeliperj** [comment]
@taviso, yes, it was fixed!!

TAB jumps a bunch of columns forward, I suppose shift-tab should jump backwards.

**Comment by sblendorio** [comment]
Sorry I got these compilation errors after "git pull"... what's happened?

![image](https://user-images.githubusercontent.com/2118813/170288993-681df010-e2f9-4bb2-86dc-094422b583d2.png)

**Comment by sblendorio** [comment]
Solved. I made a "make clean" then "make".
