### ISSUE TITLE
Pressing ESC causes a short pause

### ISSUE THREAD

**Issue by sblendorio** [taviso/123elf#37]
Using "/" menu, and pressing ESC, it takes about one second before exiting the menu and return to the edit mode on spreadsheet. It happens on Terminal Emulator in Cinnamon:

![image](https://user-images.githubusercontent.com/2118813/170511517-d37f8f66-a973-4111-b949-61fb76bdebdf.png)

Is it normal?

P.S. it does not happen on a real DEC VT320...

**Comment by taviso** [comment]
I've noticed that too, see #36 

I think this can be fixed, it's probably a default from when you might have been  using 123 over a 2400 baud modem!

**Comment by taviso** [comment]
No, I'm an idiot - I thought the setting was milliseconds, but it's deciseconds!

Patch on the way...
