### ISSUE TITLE
Undo should be enabled by default.

### ISSUE THREAD

**Issue by taviso** [taviso/123elf#43]
I think modern users will be surprised that you have to enable undo (`/Worksheet Global Default  Other Undo Enable Update`).

**Comment by multizone-uk** [comment]
This was originally because Undo used too much memory and people often had sheets which consumed all the memory available (especially in MS-DOS). You could even get Lotus-Intel-Microsoft expanded memory cards to let you page more memory in and out for gigantic sheets. - Angus
