### ISSUE TITLE
Graphs dont work

### ISSUE THREAD

**Issue by taviso** [taviso/123elf#5]
You can create a graph, but can't display it in the terminal yet -- port the driver from [lotusdrv](https://github.com/taviso/lotusdrv)!

**Comment by taviso** [comment]
I nearly have a patch working, it needs a bit more work to improve the appearance!

https://user-images.githubusercontent.com/123814/170280825-3b75e46a-489f-483d-895e-6ccd5d347b8b.mov

**Comment by taviso** [comment]
Okay, I've committed a first attempt - I think it's not bad!

Pie charts, Bar charts, Line charts, all work okay. Colors work, and *some* hatching.

You can either use `/Graph` or `F10` to show a graph. Here is the demo file I used in the video below.

[wave.zip](https://github.com/taviso/123elf/files/8776865/wave.zip)


https://user-images.githubusercontent.com/123814/170433003-195a1d51-ef9a-458c-9682-d40d027e6ca3.mov

**Comment by jibanes** [comment]
nice
