### ISSUE TITLE
Dependency: makeinfo

### ISSUE THREAD

**Issue by dtwilliamson** [taviso/123elf#59]
I had to install `makeinfo`

`sudo apt install texinfo`

before the `binutils.sh` would complete. There was a failure during `make`.

The script completed successfully after `makeinfo` was installed.

Ubuntu 18.04

**Comment by taviso** [comment]
Ah-ha you're right, I wonder if there is a configure option to disable documentation.

**Comment by taviso** [comment]
I think you can do make MAKEINFO=true, I'll add that change.
