### ISSUE TITLE
"Error reading file" on startup

### ISSUE THREAD

**Issue by taviso** [taviso/123elf#6]
Sometimes Lotus says "Error reading file" on startup. The error can be dismissed by pressing Enter, and it seems to work after that.

What file is it talking about?

**Comment by josefcub** [comment]
The advantage of strace is that it captures everything.  The major downside of strace is that it captures -everything- and you have to wade through it.

I looked for ENOENT in an strace dump, and came up with these:

```
$ grep ENOENT strace.txt 
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/chrclass/ascii", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/spool/lp/admins/lp/printers", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/spool/lp/interface", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
access("/home/josefcub/lotus.bcf", R_OK) = -1 ENOENT (No such file or directory)
access("/home/josefcub/.l123cnf", R_OK) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/josefcub/.terminfo", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_BASIC_STATS, 0xfff9d424) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "c:\\cmd0000.tmp", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_BASIC_STATS, 0xfff9e530) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/self/cwd/root/lotus/123.v10/ri/USA-English/license.ri", O_RDONLY) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/proc/self/cwd/root/lotus/log/123usage.log", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_BASIC_STATS, 0xfff9daac) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/proc/self/cwd/root/lotus/log/123usage.log", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_BASIC_STATS, 0xfff9dabc) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/self/cwd/root/lotus/log/123usage.log", O_WRONLY|O_CREAT, 0666) = -1 ENOENT (No such file or directory)
```

I haven't had much time to look at this since you fixed starting it up.  I intend to attempt to figure out what else in the filesystem it needs and where, since I know 123 for DOS (as of r2.2 anyway, the only version I've kept since childhood)  has everything in one dir, but this release definitely seems to have a more coherent structure to work through.

Hope this helps!

**Comment by taviso** [comment]
Ah-ha - thanks for the debugging output. Believe it or not, I think it's not a bug!

I think if you don't specify a file on the commandline, it will try to open `~/auto123.wk3` -- your default worksheet.

If you put a worksheet there, then the error will go away. If you specify a file, there is no error:

e.g. `$ ./123 -f unix -w  $PWD/root/lotus/123.v10/smpfiles/TABLES.WK3`

I think this is what it is trying to say in the manual (try `man ./root/lotus/man/man1/123.1`), but it isn't very clear!

**Comment by taviso** [comment]
Hmm, maybe I'm wrong, this section seems to say that it should not give an error:

```
       123

            This command runs 1-2-3 with all the defaults that you selected via the setup123 config‐
            uration utility. If there is no autoretrieve file in your default 1-2-3 directory (spec‐
            ified in /Worksheet Global Default Dir), 1-2-3 retrieves no file and  displays  a  blank
            worksheet.
```

I don't know, I'll try to trace through what it's doing.

**Comment by taviso** [comment]
Nope - it was a bug, file locking didn't work properly :)

Unfortunately if you've run 123 before, it might have created the file `~/auto123.wk3` because of the broken locking.
