### ISSUE TITLE
`cpio` fails to extract `123.o.z_2` on MacOS

### ISSUE THREAD

**Issue by dtwilliamson** [taviso/123elf#62]
MacOS `cpio` doesn't have the `-D` directory option so I used a relative reference in the command below.

When I did

```
cd root
for i in 123UNIX{2..5}.IMG; do
    cpio -id < ../${i}
done
```

The `lotus/123.v10/sysV386/lib/123.o.z_1` file (and others) extracted successfully, but `123.o.z_2` did not. I don't see any reason that this happens except that on Linux I get

> lotus/123.v10/hlp/USA-English/123_sysV.hlp.z
> cpio: warning: skipped 4798 bytes of junk
> lotus/123.v10/sysV386/dvr/l13pepdt.dvr.z
> lotus/123.v10/sysV386/lib/123.o.z_2
> 2510 blocks
> lotus/123.v10/sysV386/bin/inst_dl.z

when I use `-v`. On MacOS, I get `skipped 4798 bytes...` and the `_2` file isn't listed in the file names.

**Comment by damouze** [comment]
Devuan ascii does not have the -D option either.

**Comment by taviso** [comment]
Hmm, I'm not sure what that junk is. Let me figure out what it is, maybe we can extract the non-junk parts with dd or something.

**Comment by dtwilliamson** [comment]
What about the missing `_2` file on MacOS?

**Comment by vrza** [comment]
@dtwilliamson Should be fixed with https://github.com/taviso/123elf/pull/67

**Comment by taviso** [comment]
Thanks @vrza, marked fixed.
