### ISSUE TITLE
COFF dynamic object loader

### ISSUE THREAD

**Issue by teuben** [taviso/123elf#7]
(more of a question for you related to your article on lotus123)
Not sure if this is the kind of code you are looking for a COFF object loader, I once wrote one based off a similar one we had working in good old sunos3....  All those codes are in the NEMO package in:
https://github.com/teuben/nemo/tree/master/src/kernel/loadobj

**Comment by taviso** [comment]
Thanks, I wish I had seen that before writing my own! It looks like you have a lot of features I'm still missing though, so it's definitely a useful reference, thank you!
