### ISSUE TITLE
Can't import file due to long filename

### ISSUE THREAD

**Issue by sjuswede** [taviso/123elf#82]
To test the spreadsheet, I import some csv files of various kinds and do operations on them. I ran into a message when trying to import this file, and the file failed to import:

annual-enterprise-survey-2020-financial-year-provisional-csv.csv

The message I got at the bottom row is:

Name too long -- Press Help

When I rename the file to "annual.csv" it imports fine.

**Comment by taviso** [comment]
I found the problem, `file_validate` checks if the `strlen(name+ext)` is longer than 14 characters.

This seems like a logic error in the routine, they only intended to check if in DOS mode, but they accidentally also check in UNIX mode. I tried just removing that check in a debugger, and it works fine, imports the file no problem.

The solution is to reimplement this routine, it's a little bit complicated, but should be no problem. I'll work on it.

**Comment by taviso** [comment]
I have a hacky patch that resolves this bug, but it's big and complicated and I want to test it some more. I'm working on it!
