### ISSUE TITLE
Build breaks on missing terminal info for terminals that are not installed

### ISSUE THREAD

**Issue by sjuswede** [taviso/123elf#85]
Running Xubuntu 22.04, a fairly minimal install, except I have rxvt-unicode and screen and such.

Trying to compile latest git now gives me:

mkdir -p share/lotus/keymaps/v
keymap/keymap vte > share/lotus/keymaps/v/vte
'vte': unknown terminal type.
make: *** [Makefile:64: vte] Error 1

**Comment by sjuswede** [comment]
Now I get:

mkdir -p share/lotus/keymaps/k
keymap/keymap konsole > share/lotus/keymaps/k/konsole
'konsole': unknown terminal type.
make: *** [Makefile:64: konsole] Error 1

**Comment by taviso** [comment]
Hah, okay, I guess I'll just stick to xterm/rxvt/screen - does screen.xterm-256color work?

**Comment by sjuswede** [comment]
Yes, now it works fully. I have screen (and tmux) installed.

Maybe it would be possible to let make fail gracefully on these instead, and simply add lots of terminals? I never tried doing that in make, I always set it up with configure, but that might be overkill for this.
