### ISSUE TITLE
free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by indigoparadox** [taviso/123elf#9]
Hello!

Trying to compile on Ubuntu 20.04 using binutils-2.34 downloaded and compiled with i386-coff support. Getting the following:

```
objcopy -I coff-i386 -O coff-i386 --wildcard --localize-symbols=localize.lst --globalize-symbols=globalize.lst --redefine-syms=redefine.lst --weaken-symbols=weaken.lst orig/123.o 123.o
free(): double free detected in tcache 2
make: *** [Makefile:44: 123.o] Aborted (core dumped)
make: *** Deleting file '123.o'
```

I'm thinking this might be the result of the version of binutils I'm using? It's the same version as Ubuntu 20.04 gives me. Any ideas?

Thanks!

**Comment by taviso** [comment]
wow, you're right - I just tried it - objcopy from binutils 2.34 crashes reliably! The version distributed by Ubuntu crashes too, even though it doesn't support COFF files.

I had only tested 2.38, I guess they fixed this bug at some point -- could you try 2.38 instead?

**Comment by indigoparadox** [comment]
Sure enough, that did it! 2.38 worked great!

Had similar trouble elsewhere before... it's often a question of "is my binutils too new or too old?" Looks like it was too old in this case. :)
