### ISSUE TITLE
Arm/Mac port

### ISSUE THREAD

**Issue by Bellavene** [taviso/123elf#98]
Will be more than happy if somebody will guide to compile it for M1

**Comment by taviso** [comment]
We're actually using some of the original SystemV/386 code, so it's very tightly coupled to x86. You could run it on an Intel Mac, and it might be possible to port it to new architectures in the future but that's a long way off!

**Comment by Bellavene** [comment]
OK, let me compile x86 then, will launch it through rosetta2. When I try to compile it as is, it gives a error because tried to compile something for arm.
